<a href="https://colab.research.google.com/github/UEPP40/PUM/blob/Jablonski/05.03.2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import math
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
train = pd.read_csv('train.csv')
##train.info()
train.drop_duplicates(subset='ID',inplace= True)
FeaturesToConvert = ['Age','Annual_Income','Num_of_Loan','Num_of_Delayed_Payment','Changed_Credit_Limit','Outstanding_Debt','Amount_invested_monthly','Monthly_Balance']
df_cleaned = train.drop_duplicates(subset='ID',inplace= True)
for feature in FeaturesToConvert :
  train[feature] = train[feature].str.strip('-_')

for feature in FeaturesToConvert:
  train[feature] = train[feature].replace({'':np.nan})

for feature in FeaturesToConvert:
  train[feature] = train[feature].astype('float64')
  train['Monthly_Inhand_Salary']= train['Monthly_Inhand_Salary'].fillna(method='pad')
#le = LabelEncoder()
#train.Occupation = le.fit_transform(df.Occupation)
#train.head()
#cols = ['workex', 'status', 'hsc_s', 'degree_t']

#train[cols] =  train[cols].apply(LabelEncoder().fit_transform)

#train.head()
train.describe()

#for i in train.columns:
  #print(train[i].value_counts())
  #print('*'*50)

#sns.countplot(train['Credit_Score'])
#scaler = MinMaxScaler()
#col_float = ['Age','Annual_Income','Delay_from_due_date','Num_of_Delayed_Payment','Outstanding_Debt','Credit_History_Age','Total_EMI_per_month','Monthly_Balance']
#for i in df_cleaned[col_float]:
 # df_cleaned[i] = scaler.fit_transform(df_cleaned[[i]])
  #df_cleaned.head

<ipython-input-60-c7faf3fd8316>:9: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv('train.csv')

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance
count,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,92998.000000,97909.000000,98035.000000,100000.000000,100000.000000,100000.000000,95521.000000,9.713200e+04
mean,119.509700,1.764157e+05,4196.144246,17.091280,22.47443,72.466040,10.761960,21.068780,30.946268,10.465678,27.754251,1426.220376,32.285173,1403.118217,637.412998,3.088580e+22
std,684.757313,1.429618e+06,3187.848468,117.404834,129.05741,466.422621,61.789933,14.860104,226.028754,6.670732,193.177339,1155.129026,5.116875,8306.041270,2043.319327,3.208492e+24
min,14.000000,7.005930e+03,303.645417,-1.000000,0.00000,1.000000,0.000000,-5.000000,0.000000,0.000000,0.000000,0.230000,20.000000,0.000000,0.000000,7.759665e-03
25%,25.000000,1.945750e+04,1625.558333,3.000000,4.00000,8.000000,2.000000,10.000000,9.000000,5.350000,3.000000,566.072500,28.052567,30.306660,74.534002,2.700037e+02
50%,34.000000,3.757861e+04,3089.544583,6.000000,5.00000,13.000000,3.000000,18.000000,14.000000,9.400000,6.000000,1166.155000,32.305784,69.249473,135.925682,3.364770e+02
75%,42.000000,7.279092e+04,5957.715000,7.000000,7.00000,20.000000,6.000000,28.000000,18.000000,14.870000,9.000000,1945.962500,36.496663,161.224249,265.731733,4.696852e+02
max,8698.000000,2.419806e+07,15204.633333,1798.000000,1499.00000,5797.000000,1496.000000,67.000000,4397.000000,36.970000,2597.000000,4998.070000,50.000000,82331.000000,10000.000000,3.333333e+26