<a href="https://colab.research.google.com/github/UEPP40/PUM/blob/Stanislawska/05_03_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#importujemy biblioteki :)
import pandas as pd #ta jest do dziazłania na dataFrames(df) czyli takich jakby tabelach w pythonie
import numpy as np #to jest do działań i operacji na arrays (tablice) roznica array i dataframe - array moze byc wielowymiarowy a Df zawsze dwu wymiarowy
from sklearn.preprocessing import LabelEncoder #ta pomag przy preprocesowaniu danych (skalowanie, centryzacja, normalizacja, binaryzacja) a labelEncoder to jak nazwa mowi do odczytywania etykiet
# https://scikit-learn.org/stable/modules/preprocessing.html  -- link do dokumentacji o preprocesowaniu z tej biblio - maja fajne metody ;D

#zaczytujemy plik csv do dataframe - PAMIETAJCIE W COLABIE Z KAZDYM NOWYM URUCHOMIENIEM DANEGO NOTATNIKA MUSICIE JESZCZE RAZ RECZNIE WLOZYC PLIKI DO "FOLDERU" BO ONE SIE NIE ZAPISUJA
# jesli wrzuciliscie folder z ktorego chcecie odczytac plik to odpowiednio musicie podac sciezke "folder\plik.csv"
df = pd.read_csv("train.csv")
#df to nazwa tego dataframe pamiejtajcie taka nazwe jaka dacie tutaj trzeba uzywac juz wszedzie

# df.shape sprawdza rozmiar dataframe ale w tym kodzie nic nie wyswietli
df.shape

# usuwamy te wiersze ktore maja powtarzajace sie ID
df.drop_duplicates(subset="ID",inplace=True)

# ta petla wyswietli wszystkie wartosci unikalne dla kazdej kolumny - warto sprawdzic zeby zobaczyc czy faktycznie duplikaty sie usunely - po wykonaniu sie jej zakomentoac bo bedzie wyrzucac wielki nieczytelny output co utrudni dalsze dzialania
#for i in df.columns:
  #print(df[i].value_counts())
  #print('*'*50)

# wywolujac info sprawdzamy typy danych w kazdej kolumnie w naszym df - tez po wykonaniu lepiej zakomentowac - majac np dwa df.info() wykonuje sie tylko pierwsze
#df.info()

# na podstawie wyników z info tworzymy tablice z nazwami kolumn w ktorych chcemy dane zamienic na numeryczne
FeaturesToConvert = ['Age', 'Annual_Income', 'Num_of_Loan', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Outstanding_Debt', 'Amount_invested_monthly', 'Monthly_Balance']
# przez kilka kroków bedziemy iterowac po tej tablicy

# na początku usuwamy znaki '-' i '_' tak by nasze dane skladaly sie z samych cyfr ( i ew. kropek)
for feature in FeaturesToConvert:
   df[feature] = df[feature].str.strip('-_')

# nastepnie zamieniamy puste kolumny na nan to dokladnie dzieje sie w miejscu {'':np.nan} '' - pusta kolumna np.nan - wykorzystanie nupy do zaznaczenia ze to brakujace dane w postaci nadania mu wartosci NaN - Not a Number
# więcej o np.nan tutaj : https://appdividend.com/2022/01/28/np-nan/  i o ty czym jest sam NaN tutaj: https://stackoverflow.com/questions/59335027/what-is-nan-not-a-number-in-the-words-of-a-beginner
for feature in FeaturesToConvert:
   df[feature] = df[feature].replace({'':np.nan})

# tutaj bedziemy zamieniac typy danych - zamieniamy na float po to by wszytskie byly w tym samym formacie i dlatego ze w pierwotnej tabeli znajdowaly sie wartosci zmiennoprzecinkowe a zamienienie ich na in (calkoowite) zaburzy wyniki calej "zabawy"
for feature in FeaturesToConvert:
   df[feature] = df[feature].astype('float64')

# teraz nastepuje uzupelnienie pustych wartosci w kolumnach srednia badz inna odpowiednia wartoscia ktora trzeba dla kazdej kolumny dobrac indywdualnie na podstawie tego co sie w niej znajduje
# kolumny ktore trzeba uzupelnic mozna znowu sprawdzic za pomoca df.info()
#df.info()

# Uzupełnienie Monthly_Inhand_Salary wartością średnią
df['Monthly_Inhand_Salary']= df['Monthly_Inhand_Salary'].fillna(method='pad')

# Uzupełnienie ID wartością "Brak informacji"
df['ID'] = df['ID'].fillna('Brak informacji')

# Uzupełnienie Customer_ID wartością "Brak informacji"
df['Customer_ID'] = df['Customer_ID'].fillna('Brak informacji')

# Uzupełnienie Month wartością "Brak informacji"
df['Month'] = df['Month'].fillna('Brak informacji')

# Uzupełnienie Name wartością "Nieznane"
df['Name'] = df['Name'].fillna('Nieznane')

# W przypadku wieku musimy pozbyć sie tez wartosci powyzej 100 i ponizej 1 dlatego najpierw obliczamy srednia ieku pomijajac wczesniej wymienione przypadki
age_mean = df[(df['Age'] <= 100) & (df['Age'] >= 1)]['Age'].mean()
# Zamieniamy puste wartosci na ta wartosc sredniej
df['Age'] = df['Age'].fillna(age_mean)
# Nastepnie używamy funkcji .loc[] żeby znaleźć wartości powyżej 100 i poniżej 1 i zamienić je na wartość średnią
df.loc[df['Age'] >= 100, 'Age'] = age_mean
df.loc[df['Age'] < 1, 'Age'] = age_mean

# Uzupełnienie SSN wartością "Brak informacji"
df['SSN'] = df['SSN'].fillna('Brak informacji')

# Uzupełnienie Occupation wartością "Brak informacji"
df['Occupation'] = df['Occupation'].fillna('Brak informacji')

# Uzupełnienie Annual_Income wartością średnią
df['Annual_Income'] = df['Annual_Income'].fillna(method='pad')

# Uzupełnienie Num_Bank_Accounts wartością 0
df['Num_Bank_Accounts'] = df['Num_Bank_Accounts'].fillna(0)

# Uzupełnienie Num_Credit_Card wartością 0
df['Num_Credit_Card'] = df['Num_Credit_Card'].fillna(0)

# Uzupełnienie Interest_Rate wartością 0
df['Interest_Rate'] = df['Interest_Rate'].fillna(0)

# Uzupełnienie Num_of_Loan wartością 0
df['Num_of_Loan'] = df['Num_of_Loan'].fillna(0)

# Uzupełnienie Type_of_Loan wartością "Nieokreślony"
df['Type_of_Loan'] = df['Type_of_Loan'].fillna('Nieokreślony')

# Uzupełnienie Delay_from_due_date wartością 0
df['Delay_from_due_date'] = df['Delay_from_due_date'].fillna(0)

# Uzupełnienie Num_of_Delayed_Payment wartością 0
df['Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].fillna(0)

# Uzupełnienie Changed_Credit_Limit wartością 0
df['Changed_Credit_Limit'] = df['Changed_Credit_Limit'].fillna(0)

# Uzupełnienie Num_Credit_Inquiries wartością 0
df['Num_Credit_Inquiries'] = df['Num_Credit_Inquiries'].fillna(0)

# Uzupełnienie Credit_Mix wartością "Nieznane"
df['Credit_Mix'] = df['Credit_Mix'].fillna('Nieznane')

# Uzupełnienie Outstanding_Debt wartością 0
df['Outstanding_Debt'] = df['Outstanding_Debt'].fillna(0)

# Uzupełnienie Credit_Utilization_Ratio wartością 0
df['Credit_Utilization_Ratio'] = df['Credit_Utilization_Ratio'].fillna(0)

# Uzupełnienie Credit_History_Age wartością "Brak historii kredytowej"
df['Credit_History_Age'] = df['Credit_History_Age'].fillna('Brak historii kredytowej')

# Uzupełnienie Payment_of_Min_Amount wartością "Brak informacji"
df['Payment_of_Min_Amount'] = df['Payment_of_Min_Amount'].fillna('Brak informacji')

# Uzupełnienie Total_EMI_per_month wartością średnią
df['Total_EMI_per_month'] = df['Total_EMI_per_month'].fillna(method='pad')

# Uzupełnienie Amount_invested_monthly wartością średnią
df['Amount_invested_monthly'] = df['Amount_invested_monthly'].fillna(method='pad')

# Uzupełnienie Payment_Behaviour wartością "Brak informacji"
df['Payment_Behaviour'] = df['Payment_Behaviour'].fillna('Brak informacji')

# Uzupełnienie Monthly_Balance wartością średnią
df['Monthly_Balance'] = df['Monthly_Balance'].fillna(method='pad')

# Uzupełnienie Credit_Score wartością "Brak informacji"
df['Credit_Score'] = df['Credit_Score'].fillna('Brak informacji')

# tworzymy obiekt encodera czyli po prostu tworzymy nowy obiekt klasy LabelEncoder(ktora jest zdefiniowana w kodzie biblioteki) ktory przypisujemy do zmiennej le
# dokumentacja Encodera - https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
# kod klasy LabelEncoder - https://github.com/scikit-learn/scikit-learn/blob/5c4aa5d0d/sklearn/preprocessing/_label.py#L34
le = LabelEncoder()

# Jako przykład zakodujmy wartości dla kolumny Age, zwrócone zostają wartości zakodowane (dla ambitnych podrzucam kod funkcji i kod funkcji wykorzystywanej w fit_transform https://github.com/scikit-learn/scikit-learn/blob/5c4aa5d0d/sklearn/preprocessing/_label.py#L101  https://github.com/scikit-learn/scikit-learn/blob/5c4aa5d0d90ba66247d675d4c3fc2fdfba3c39ff/sklearn/utils/_encode.py#L10)
df.Age = le.fit_transform(df.Age)

# df.head jest tylko do sprawdzenia czy kodowanie sie powiodło po sprawdzeniu najlepiej zakomentowac
#df.head()

# kodowanie dla kilku kolumn odbywa sie podobnie tylko najpierw musimy zadefiniowac tablice z nazwami kolumn które mają przejść transformację
# dałam tylko kilka dla przykładu działania
columns_to_code = ['Occupation','Annual_Income','Monthly_Balance', 'Credit_Score']

# dzięki apply możemy za jednym wywołaniem kodu wykonać daną operację na każdym elemencie z listy
df[columns_to_code] = df[columns_to_code].apply(LabelEncoder().fit_transform)

# znowu df.head() dla sprawdzenia czy działa
df.head()

<ipython-input-16-185c413669bf>:9: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("train.csv")

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.415295,High_spent_Small_value_payments,40780,0
1,0x1603,CUS_0xd40,February,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,31.944960,Brak historii kredytowej,No,49.574949,118.280222,Low_spent_Large_value_payments,30114,0
2,0x1604,CUS_0xd40,March,Aaron Maashoh,20,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521,Low_spent_Medium_value_payments,46907,0
3,0x1605,CUS_0xd40,April,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.458074,Low_spent_Small_value_payments,10564,0
4,0x1606,CUS_0xd40,May,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153,High_spent_Medium_value_payments,50026,0