In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram
import seaborn as sns
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.preprocessing import LabelEncoder
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import csv

In [63]:

with open('GroceryStoreDataSet.csv', 'r') as f:
    reader = csv.reader(f)
    dataset = list(reader)

print(dataset)

[['MILK', 'BREAD', 'BISCUIT'], ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'], ['BREAD', 'TEA', 'BOURNVITA'], ['JAM', 'MAGGI', 'BREAD', 'MILK'], ['MAGGI', 'TEA', 'BISCUIT'], ['BREAD', 'TEA', 'BOURNVITA'], ['MAGGI', 'TEA', 'CORNFLAKES'], ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'], ['JAM', 'MAGGI', 'BREAD', 'TEA'], ['BREAD', 'MILK'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'COCK'], ['BREAD', 'SUGER', 'BISCUIT'], ['COFFEE', 'SUGER', 'CORNFLAKES'], ['BREAD', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'SUGER'], ['BREAD', 'COFFEE', 'SUGER'], ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [64]:

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary
te_ary.astype("int")

te.columns_

['BISCUIT',
 'BOURNVITA',
 'BREAD',
 'COCK',
 'COFFEE',
 'CORNFLAKES',
 'JAM',
 'MAGGI',
 'MILK',
 'SUGER',
 'TEA']

In [78]:
import pandas as pd

pd.DataFrame(te_ary, columns=te.columns_)

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

In [85]:
a = TransactionEncoder()
a_data = a.fit(dataset).transform(dataset) ## !!data – lista list
print(a_data)

[[ True False  True False False False False False  True False False]
 [ True False  True False False  True False False  True False False]
 [False  True  True False False False False False False False  True]
 [False False  True False False False  True  True  True False False]
 [ True False False False False False False  True False False  True]
 [False  True  True False False False False False False False  True]
 [False False False False False  True False  True False False  True]
 [ True False  True False False False False  True False False  True]
 [False False  True False False False  True  True False False  True]
 [False False  True False False False False False  True False False]
 [ True False False  True  True  True False False False False False]
 [ True False False  True  True  True False False False False False]
 [False  True False False  True False False False False  True False]
 [False False  True  True  True False False False False False False]
 [ True False  True False False False False False False  True False]
 [False False False False  True  True False False False  True False]
 [False  True  True False False False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False False False  True  True False False  True False  True]]

In [92]:
df = apriori(pd.DataFrame(a_data, columns=te.columns_), min_support = 0.2, use_colnames = True, verbose = 1)
df_ar = association_rules(df, metric = "confidence"
, min_threshold = 0.6)

print(df_ar)

Processing 42 combinations | Sampling itemset size 3
    antecedents consequents  antecedent support  consequent support  support  \
0        (MILK)     (BREAD)                0.25                0.65      0.2
1       (SUGER)     (BREAD)                0.30                0.65      0.2
2  (CORNFLAKES)    (COFFEE)                0.30                0.40      0.2
3       (SUGER)    (COFFEE)                0.30                0.40      0.2
4       (MAGGI)       (TEA)                0.25                0.35      0.2

   confidence      lift  leverage  conviction  zhangs_metric
0    0.800000  1.230769    0.0375        1.75       0.250000
1    0.666667  1.025641    0.0050        1.05       0.035714
2    0.666667  1.666667    0.0800        1.80       0.571429
3    0.666667  1.666667    0.0800        1.80       0.571429
4    0.800000  2.285714    0.1125        3.25       0.750000