<a href="https://colab.research.google.com/github/UEPP40/PUM/blob/matusiak/czyszczenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Przetwarzanie wstępne danych (data preprocessing) - czyszczenie danych

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("train.csv")
df.shape

<ipython-input-3-a1dd6b4c0427>:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("train.csv")

(100000, 28)

In [4]:
df.drop_duplicates(subset="ID",inplace=True)

FeaturesToConvert = ['Age', 'Annual_Income', 'Num_of_Loan', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 'Outstanding_Debt', 'Amount_invested_monthly', 'Monthly_Balance']

for feature in FeaturesToConvert:
   df[feature] = df[feature].str.strip('-_')

for feature in FeaturesToConvert:
   df[feature] = df[feature].replace({'':np.nan})

for feature in FeaturesToConvert:
   df[feature] = df[feature].astype('float64')

In [5]:
df['Monthly_Inhand_Salary']= df['Monthly_Inhand_Salary'].fillna(method='pad')
df['ID'] = df['ID'].fillna('Brak informacji')
df['Customer_ID'] = df['Customer_ID'].fillna('Brak informacji')
df['Month'] = df['Month'].fillna('Brak informacji')
df['Name'] = df['Name'].fillna('Nieznane')

age_mean = df[(df['Age'] <= 100) & (df['Age'] >= 1)]['Age'].mean()
df['Age'] = df['Age'].fillna(age_mean)

df.loc[df['Age'] >= 100, 'Age'] = age_mean
df.loc[df['Age'] < 1, 'Age'] = age_mean

df['SSN'] = df['SSN'].fillna('Brak informacji')
df['Occupation'] = df['Occupation'].fillna('Brak informacji')
df['Annual_Income'] = df['Annual_Income'].fillna(method='pad')
df['Num_Bank_Accounts'] = df['Num_Bank_Accounts'].fillna(0)
df['Num_Credit_Card'] = df['Num_Credit_Card'].fillna(0)
df['Interest_Rate'] = df['Interest_Rate'].fillna(0)
df['Num_of_Loan'] = df['Num_of_Loan'].fillna(0)
df['Type_of_Loan'] = df['Type_of_Loan'].fillna('Nieokreślony')
df['Delay_from_due_date'] = df['Delay_from_due_date'].fillna(0)
df['Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].fillna(0)
df['Changed_Credit_Limit'] = df['Changed_Credit_Limit'].fillna(0)
df['Num_Credit_Inquiries'] = df['Num_Credit_Inquiries'].fillna(0)
df['Credit_Mix'] = df['Credit_Mix'].fillna('Nieznane')
df['Outstanding_Debt'] = df['Outstanding_Debt'].fillna(0)
df['Credit_Utilization_Ratio'] = df['Credit_Utilization_Ratio'].fillna(0)
df['Credit_History_Age'] = df['Credit_History_Age'].fillna('Brak historii kredytowej')
df['Payment_of_Min_Amount'] = df['Payment_of_Min_Amount'].fillna('Brak informacji')
df['Total_EMI_per_month'] = df['Total_EMI_per_month'].fillna(method='pad')
df['Amount_invested_monthly'] = df['Amount_invested_monthly'].fillna(method='pad')
df['Payment_Behaviour'] = df['Payment_Behaviour'].fillna('Brak informacji')
df['Monthly_Balance'] = df['Monthly_Balance'].fillna(method='pad')
df['Credit_Score'] = df['Credit_Score'].fillna('Brak informacji')

le = LabelEncoder()
df.Age = le.fit_transform(df.Age)
columns_to_code = ['Occupation','Annual_Income','Monthly_Balance', 'Credit_Score']

df[columns_to_code] = df[columns_to_code].apply(LabelEncoder().fit_transform)

df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.415295,High_spent_Small_value_payments,40780,0
1,0x1603,CUS_0xd40,February,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,31.944960,Brak historii kredytowej,No,49.574949,118.280222,Low_spent_Large_value_payments,30114,0
2,0x1604,CUS_0xd40,March,Aaron Maashoh,20,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521,Low_spent_Medium_value_payments,46907,0
3,0x1605,CUS_0xd40,April,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.458074,Low_spent_Small_value_payments,10564,0
4,0x1606,CUS_0xd40,May,Aaron Maashoh,9,821-00-0265,12,3021,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153,High_spent_Medium_value_payments,50026,0