<a href="https://colab.research.google.com/github/UEPP40/PUM/blob/Maksim/linear_regression_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from google.colab import files
uploaded = files.upload()

Saving salary_data.csv to salary_data (1).csv

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
df = pd.read_csv('salary_data.csv')

In [25]:
df.head(50)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0
10,29.0,Male,Master's,Software Developer,3.0,75000.0
11,48.0,Female,Bachelor's,HR Manager,18.0,140000.0
12,35.0,Male,Bachelor's,Financial Analyst,6.0,65000.0
13,40.0,Female,Master's,Project Manager,14.0,130000.0
14,27.0,Male,Bachelor's,Customer Service Rep,2.0,40000.0
15,44.0,Male,Bachelor's,Operations Manager,16.0,125000.0
16,33.0,Female,Master's,Marketing Manager,7.0,90000.0
17,39.0,Male,PhD,Senior Engineer,12.0,115000.0
18,25.0,Female,Bachelor's,Data Entry Clerk,0.0,35000.0
19,51.0,Male,Bachelor's,Sales Director,22.0,180000.0
20,34.0,Female,Master's,Business Analyst,5.0,80000.0
21,47.0,Male,Master's,VP of Operations,19.0,190000.0
22,30.0,Male,Bachelor's,IT Support,2.0,50000.0
23,36.0,Female,Bachelor's,Recruiter,9.0,60000.0
24,41.0,Male,Master's,Financial Manager,13.0,140000.0
25,28.0,Female,Bachelor's,Social Media Specialist,3.0,45000.0
26,37.0,Female,Master's,Software Manager,11.0,110000.0
27,24.0,Male,Bachelor's,Junior Developer,1.0,40000.0
28,43.0,Female,PhD,Senior Consultant,15.0,140000.0
29,33.0,Male,Master's,Product Designer,6.0,90000.0
30,50.0,Male,Bachelor's,CEO,25.0,250000.0
31,31.0,Female,Bachelor's,Accountant,4.0,55000.0
32,29.0,Male,Master's,Data Scientist,3.0,75000.0
33,39.0,Female,Bachelor's,Marketing Specialist,10.0,65000.0
34,46.0,Male,PhD,Senior Manager,20.0,170000.0
35,27.0,Male,Bachelor's,Technical Writer,2.0,45000.0
36,35.0,Female,Bachelor's,HR Generalist,7.0,60000.0
37,42.0,Male,Master's,Project Engineer,14.0,115000.0
38,26.0,Female,Bachelor's,Customer Success Rep,1.0,40000.0
39,49.0,Male,Bachelor's,Sales Executive,21.0,160000.0
40,34.0,Female,Master's,UX Designer,5.0,80000.0
41,48.0,Male,Master's,Operations Director,18.0,190000.0
42,30.0,Male,Bachelor's,Network Engineer,3.0,60000.0
43,36.0,Female,Bachelor's,Administrative Assistant,8.0,45000.0
44,41.0,Male,Master's,Strategy Consultant,13.0,130000.0
45,28.0,Female,Bachelor's,Copywriter,2.0,40000.0
46,32.0,Male,Bachelor's,Account Manager,5.0,75000.0
47,45.0,Female,Master's,Director of Marketing,16.0,180000.0
48,38.0,Male,PhD,Senior Scientist,11.0,120000.0
49,25.0,Male,Bachelor's,Help Desk Analyst,0.0,35000.0

In [26]:
df.dtypes

Age                    float64
Gender                  object
Education Level         object
Job Title               object
Years of Experience    float64
Salary                 float64
dtype: object

In [27]:
df.shape

(375, 6)

In [28]:
df.dropna(inplace=True)

In [29]:
df['Gender'] = (df['Gender']).astype('string')
df['Education Level'] = (df['Education Level']).astype('string')
df['Job Title'] = (df['Job Title']).astype('string')

In [30]:
df.dtypes

Age                    float64
Gender                  string
Education Level         string
Job Title               string
Years of Experience    float64
Salary                 float64
dtype: object

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
from sklearn.preprocessing import LabelEncoder
import math

In [33]:
columns = ['Gender', 'Education Level', 'Job Title']
# Encode labels of multiple columns at once
df[columns] =df[columns].apply(LabelEncoder().fit_transform)

In [34]:
df.head()

    Age  Gender  Education Level  Job Title  Years of Experience    Salary
0  32.0       1                0        159                  5.0   90000.0
1  28.0       0                1         17                  3.0   65000.0
2  45.0       1                2        130                 15.0  150000.0
3  36.0       0                0        101                  7.0   60000.0
4  52.0       1                1         22                 20.0  200000.0

In [38]:
education_mapping = {"Bachelor's":1, "Master's":2, "PhD":3}
df["Education Level"] = df["Education Level"].map(education_mapping).astype('int32')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [35]:
X = df.drop(columns=['Salary'])
y = df['Salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Rozmiar zbioru treningowego:", len(X_train))
print("Rozmiar zbioru testowego:", len(X_test))

Rozmiar zbioru treningowego: 261
Rozmiar zbioru testowego: 112

In [36]:
model = LinearRegression()

model.fit(X_train, y_train)

y_predicted = model.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print("Błąd średni absolutny:", mae)

Błąd średni absolutny: 11377.183126703107

In [37]:
from sklearn.metrics import median_absolute_error
median_absolute_error(y_test, y_predicted)

8320.821301534226